# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_error_message <- function() {
    .Call(`_wspp070_get_error_message`)
}

#' @export
cplusplus <- function() {
    .Call(`_wspp070_cplusplus`)
}

