// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_error_message
std::string get_error_message();
RcppExport SEXP _wspp051_get_error_message() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_error_message());
    return rcpp_result_gen;
END_RCPP
}
// cplusplus
int cplusplus();
RcppExport SEXP _wspp051_cplusplus() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cplusplus());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wspp051_get_error_message", (DL_FUNC) &_wspp051_get_error_message, 0},
    {"_wspp051_cplusplus", (DL_FUNC) &_wspp051_cplusplus, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_wspp051(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
